"""Catalog for the companion hymnal.

IDs are stable and independent of section order. A text and a tune are distinct
works: assigning a tune here does not authorize reproducing an arrangement.
"""

SECTIONS = [
    ("praise", "Praise and wonder"),
    ("trust", "Trust and guidance"),
    ("christ", "Christ and salvation"),
    ("advent_christmas", "Advent and Christmas"),
]

CHAPTERS = [
    ("requested", "The original fourteen",
     "The hymns that began this collection."),
    ("related", "Related hymns",
     "Companion hymns chosen to continue the themes of the original fourteen."),
    ("advent_christmas", "Advent and Christmas",
     "Advent hymns voice expectation; Christmas and Epiphany hymns celebrate "
     "the birth and revelation of Christ."),
]

TUNES = {
    "old-hundredth": {"name": "OLD HUNDREDTH", "source": "Louis Bourgeois, 1551"},
    "nettleton": {"name": "NETTLETON", "source": "Traditional American tune"},
    "lobe-den-herren": {"name": "LOBE DEN HERREN", "source": "German chorale"},
    "slane": {"name": "SLANE", "source": "Traditional Irish melody"},
    "ein-feste-burg": {"name": "EIN FESTE BURG", "source": "Martin Luther"},
    "nicaea": {"name": "NICAEA", "source": "John Bacchus Dykes"},
    "faithfulness": {"name": "FAITHFULNESS", "source": "William M. Runyan, 1923"},
    "lasst-uns-erfreuen": {"name": "LASST UNS ERFREUEN", "source": "German hymn tune, 1623"},
    "hallelujah-what-a-savior": {"name": "HALLELUJAH! WHAT A SAVIOR!", "source": "Philip P. Bliss, 1875"},
}

# text_rights describes the selected words, not every version of the hymn.
# "pending" means no edition has yet been chosen and cleared for inclusion.
HYMNS = [
    dict(id="h001", title="Doxology", first_line="Praise God, from whom all blessings flow",
         author="Thomas Ken", section="praise", tune="old-hundredth", meter="L.M.",
         text_rights="public_domain", text_edition="The Army and Navy Hymnal (1920), no. 240",
         source="https://en.wikisource.org/wiki/The_Army_and_Navy_Hymnal/Hymns/Praise_God%2C_from_Whom_All_Blessings_Flow"),
    dict(id="h002", title="Come, Thou Fount of Every Blessing", first_line="Come, thou Fount of every blessing",
         author="Robert Robinson", section="trust", tune="nettleton", meter="8.7.8.7 D",
         text_rights="public_domain", text_edition="A Collection of Gospel Hymns in Ojibway and English (1890), hymn 20",
         source="https://www.gutenberg.org/files/33128/33128-h/33128-h.htm#h20"),
    dict(id="h003", title="Praise to the Lord, the Almighty", first_line="Praise to the Lord, the Almighty, the King of creation",
         author="Joachim Neander; translated by Catherine Winkworth", section="praise",
         tune="lobe-den-herren", text_rights="public_domain",
         text_edition="Evangelical Lutheran Hymn-Book (1912), no. 63",
         source="https://www.gutenberg.org/files/76498/76498-h/76498-h.htm#hymn_63"),
    dict(id="h004", title="How Great Thou Art", first_line="O Lord my God, when I in awesome wonder",
         author="Stuart K. Hine", section="praise", text_rights="permission_required",
         source="https://hymnary.org/text/o_lord_my_god_when_i_in_awesome_wonder"),
    dict(id="h005", title="Great Is Thy Faithfulness", first_line="Great is thy faithfulness, O God my Father",
         author="Thomas O. Chisholm", section="trust", tune="faithfulness",
         source="https://www.hymnologyarchive.com/great-is-thy-faithfulness"),
    dict(id="h006", title="All Creatures of Our God and King", first_line="All creatures of our God and King",
         author="Francis of Assisi; paraphrased by William H. Draper", section="praise",
         tune="lasst-uns-erfreuen",
         source="https://github.com/mzealey/openhymnal/blob/master/Complete/All_Creatures_Of_Our_God_And_King/All_Creatures_Of_Our_God_And_King-Lasst_Uns_Erfreuen.abc"),
    dict(id="h007", title="The Solid Rock", first_line="My hope is built on nothing less",
         author="Edward Mote", section="trust", text_rights="public_domain",
         text_edition="Evangelical Lutheran Hymn-Book (1912), no. 306",
         source="https://www.gutenberg.org/files/76498/76498-h/76498-h.htm#hymn_306"),
    dict(id="h008", title="Fairest Lord Jesus", first_line="Fairest Lord Jesus, ruler of all nature",
         author="Traditional German; English translation varies", section="christ",
         text_rights="public_domain", text_edition="The Army and Navy Hymnal (1920), no. 57",
         source="https://en.wikisource.org/wiki/The_Army_and_Navy_Hymnal/Hymns/Fairest_Lord_Jesus"),
    dict(id="h009", title="Savior, Like a Shepherd Lead Us", first_line="Savior, like a shepherd lead us",
         author="Attributed to Dorothy A. Thrupp", section="trust", text_rights="public_domain",
         text_edition="The Bible Story (1917), vol. 5, p. 309",
         source="https://www.gutenberg.org/cache/epub/32736/pg32736-images.html#I.309"),
    dict(id="h010", title="Be Thou My Vision", first_line="Be thou my vision, O Lord of my heart",
         author="Irish text; versified in English by Eleanor Hull", section="trust", tune="slane",
         text_rights="public_domain", text_edition="Eleanor Hull, The Poem-Book of the Gael (1912), pp. 119–120",
         source="https://www.gutenberg.org/cache/epub/46917/pg46917-images.html#A_PRAYER"),
    dict(id="h011", title="A Mighty Fortress Is Our God", first_line="A mighty fortress is our God",
         author="Martin Luther; English translation in the 1912 hymnal", section="trust", tune="ein-feste-burg",
         text_rights="public_domain", text_edition="Evangelical Lutheran Hymn-Book (1912), no. 273",
         source="https://www.gutenberg.org/files/76498/76498-h/76498-h.htm#hymn_273"),
    dict(id="h012", title="It Is Well with My Soul", first_line="When peace like a river attendeth my way",
         author="Horatio G. Spafford", section="trust", text_rights="public_domain",
         text_edition="The Canadian Soldiers' Song Book (1919), no. 161",
         source="https://en.wikisource.org/wiki/The_Canadian_Soldiers%27_Song_Book/When_Peace_Like_a_River"),
    dict(id="h013", title="Hallelujah! What a Savior", first_line="Man of sorrows! What a name",
         author="Philip P. Bliss", section="christ", tune="hallelujah-what-a-savior",
         source="https://github.com/mzealey/openhymnal/blob/master/Complete/Hallelujah_What_a_Savior/Hallelujah_What_a_Savior-Hallelujah_What_a_Savior.abc"),
    dict(id="h014", title="Holy, Holy, Holy! Lord God Almighty!", first_line="Holy, holy, holy! Lord God Almighty",
         author="Reginald Heber", section="praise", tune="nicaea",
         text_rights="public_domain", text_edition="The Army and Navy Hymnal (1920), no. 4",
         source="https://en.wikisource.org/wiki/The_Army_and_Navy_Hymnal/Hymns/Holy%2C_Holy%2C_Holy%2C_Lord_God_Almighty"),
]

# Companion choices connect to one of the requested hymns. These are linked
# catalog entries until a particular text edition is selected and documented.
HYMNS.extend([
    dict(id="h015", title="Amazing Grace", first_line="Amazing grace! how sweet the sound",
         author="John Newton", section="trust", related_to="h002",
         source="https://hymnary.org/text/amazing_grace_how_sweet_the_sound"),
    dict(id="h016", title="How Firm a Foundation", first_line="How firm a foundation, ye saints of the Lord",
         author="K. (attribution disputed)", section="trust", related_to="h007",
         source="https://hymnary.org/text/how_firm_a_foundation_ye_saints_of"),
    dict(id="h017", title="Rock of Ages", first_line="Rock of Ages, cleft for me",
         author="Augustus M. Toplady", section="trust", related_to="h007",
         source="https://hymnary.org/text/rock_of_ages_cleft_for_me_let_me_hide"),
    dict(id="h018", title="Blessed Assurance", first_line="Blessed assurance, Jesus is mine",
         author="Fanny J. Crosby", section="trust", related_to="h012",
         source="https://hymnary.org/text/blessed_assurance_jesus_is_mine"),
    dict(id="h019", title="What a Friend We Have in Jesus", first_line="What a friend we have in Jesus",
         author="Joseph M. Scriven", section="trust", related_to="h012",
         source="https://hymnary.org/text/what_a_friend_we_have_in_jesus_all_our_s"),
    dict(id="h020", title="'Tis So Sweet to Trust in Jesus", first_line="'Tis so sweet to trust in Jesus",
         author="Louisa M. R. Stead", section="trust", related_to="h005",
         source="https://hymnary.org/text/tis_so_sweet_to_trust_in_jesus_just_to"),
    dict(id="h021", title="The King of Love My Shepherd Is", first_line="The King of love my Shepherd is",
         author="Henry W. Baker", section="trust", related_to="h009",
         source="https://hymnary.org/text/the_king_of_love_my_shepherd_is"),
    dict(id="h022", title="Jesus, Lover of My Soul", first_line="Jesus, lover of my soul",
         author="Charles Wesley", section="trust", related_to="h009",
         source="https://hymnary.org/text/jesus_lover_of_my_soul_let_me_to_thy_bos"),
    dict(id="h023", title="I Need Thee Every Hour", first_line="I need thee every hour",
         author="Annie S. Hawks", section="trust", related_to="h009",
         source="https://hymnary.org/text/i_need_thee_every_hour_most_gracious_lor"),
    dict(id="h024", title="Abide with Me", first_line="Abide with me; fast falls the eventide",
         author="Henry F. Lyte", section="trust", related_to="h012",
         source="https://hymnary.org/text/abide_with_me_fast_falls_the_eventide"),
    dict(id="h025", title="Leaning on the Everlasting Arms", first_line="What a fellowship, what a joy divine",
         author="Elisha A. Hoffman", section="trust", related_to="h009",
         source="https://hymnary.org/text/what_a_fellowship_what_a_joy_divine"),
    dict(id="h026", title="Like a River Glorious", first_line="Like a river glorious is God's perfect peace",
         author="Frances R. Havergal", section="trust", related_to="h012",
         source="https://hymnary.org/text/like_a_river_glorious"),
    dict(id="h027", title="Take My Life, and Let It Be", first_line="Take my life and let it be",
         author="Frances R. Havergal", section="trust", related_to="h010",
         source="https://hymnary.org/text/take_my_life_and_let_it_be"),
    dict(id="h028", title="This Is My Father's World", first_line="This is my Father's world",
         author="Maltbie D. Babcock", section="praise", related_to="h006",
         source="https://hymnary.org/text/this_is_my_fathers_world_and_to_my"),
    dict(id="h029", title="O Worship the King", first_line="O worship the King, all glorious above",
         author="Robert Grant", section="praise", related_to="h003",
         source="https://hymnary.org/text/o_worship_the_king_all_glorious_above"),
    dict(id="h030", title="Immortal, Invisible, God Only Wise", first_line="Immortal, invisible, God only wise",
         author="Walter C. Smith", section="praise", related_to="h014",
         source="https://hymnary.org/text/immortal_invisible_god_only_wise"),
    dict(id="h031", title="All Hail the Power of Jesus' Name", first_line="All hail the power of Jesus' name",
         author="Edward Perronet", section="praise", related_to="h014",
         source="https://hymnary.org/text/all_hail_the_power_of_jesus_name_let"),
    dict(id="h032", title="To God Be the Glory", first_line="To God be the glory, great things he hath done",
         author="Fanny J. Crosby", section="praise", related_to="h001",
         source="https://hymnary.org/text/to_god_be_the_glory_great_things_he_hath"),
    dict(id="h033", title="Praise, My Soul, the King of Heaven", first_line="Praise, my soul, the King of heaven",
         author="Henry F. Lyte", section="praise", related_to="h003",
         source="https://hymnary.org/text/praise_my_soul_the_king_of_heaven"),
    dict(id="h034", title="Joyful, Joyful, We Adore Thee", first_line="Joyful, joyful, we adore thee",
         author="Henry van Dyke", section="praise", related_to="h006",
         source="https://hymnary.org/text/joyful_joyful_we_adore_thee"),
    dict(id="h035", title="When I Survey the Wondrous Cross", first_line="When I survey the wondrous cross",
         author="Isaac Watts", section="christ", related_to="h013",
         source="https://hymnary.org/text/when_i_survey_the_wondrous_cross_watts"),
    dict(id="h036", title="Jesus Paid It All", first_line="I hear the Savior say",
         author="Elvina M. Hall", section="christ", related_to="h013",
         source="https://hymnary.org/text/i_hear_the_savior_say_thy_strength_indee"),
    dict(id="h037", title="And Can It Be", first_line="And can it be that I should gain",
         author="Charles Wesley", section="christ", related_to="h013",
         source="https://hymnary.org/text/and_can_it_be_that_i_should_gain"),
    dict(id="h038", title="The Old Rugged Cross", first_line="On a hill far away stood an old rugged cross",
         author="George Bennard", section="christ", related_to="h013",
         source="https://hymnary.org/text/on_a_hill_far_away_stood_an_old_rugged"),
    dict(id="h039", title="O the Deep, Deep Love of Jesus", first_line="O the deep, deep love of Jesus",
         author="Samuel T. Francis", section="christ", related_to="h013",
         source="https://hymnary.org/text/o_the_deep_deep_love_of_jesus"),
])

# The seasonal chapter combines longstanding Advent and Christmas favorites.
# It includes 16 works in CCEL's historical most-published Christmas list;
# the remainder are familiar seasonal hymns documented by Hymnary.
HYMNS.extend([
    dict(id="h040", title="O Come, O Come, Emmanuel", first_line="O come, O come, Emmanuel",
         author="Latin antiphons; English translation by John Mason Neale", section="advent_christmas",
         season="Advent", source="https://hymnary.org/text/o_come_o_come_emmanuel_and_ransom"),
    dict(id="h041", title="Come, Thou Long-Expected Jesus", first_line="Come, thou long-expected Jesus",
         author="Charles Wesley", section="advent_christmas", season="Advent",
         source="https://hymnary.org/text/come_thou_long_expected_jesus_born_to"),
    dict(id="h042", title="Wake, Awake, for Night Is Flying", first_line="Wake, awake, for night is flying",
         author="Philipp Nicolai; translated by Catherine Winkworth", section="advent_christmas",
         season="Advent", source="https://hymnary.org/text/wake_awake_for_night_is_flying_winkworth"),
    dict(id="h043", title="On Jordan's Bank the Baptist's Cry", first_line="On Jordan's bank the Baptist's cry",
         author="Charles Coffin; translated by John Chandler", section="advent_christmas",
         season="Advent", source="https://hymnary.org/text/on_jordans_bank_the_baptists_cry"),
    dict(id="h044", title="Lo, How a Rose E'er Blooming", first_line="Lo, how a rose e'er blooming",
         author="Traditional German; English translation varies", section="advent_christmas",
         season="Advent", source="https://hymnary.org/text/lo_how_a_rose_eer_blooming"),
    dict(id="h045", title="Joy to the World", first_line="Joy to the world! the Lord is come",
         author="Isaac Watts", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/joy_to_the_world_the_lord_is_come"),
    dict(id="h046", title="Hark! The Herald Angels Sing", first_line="Hark! the herald angels sing",
         author="Charles Wesley", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/hark_the_herald_angels_sing_glory_to"),
    dict(id="h047", title="While Shepherds Watched Their Flocks", first_line="While shepherds watched their flocks by night",
         author="Nahum Tate", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/while_shepherds_watched_their_flocks_by"),
    dict(id="h048", title="Brightest and Best of the Sons of the Morning",
         first_line="Brightest and best of the sons of the morning", author="Reginald Heber",
         section="advent_christmas", season="Christmas and Epiphany",
         source="https://hymnary.org/text/brightest_and_best_of_the_sons_of_the_mo"),
    dict(id="h049", title="It Came Upon the Midnight Clear", first_line="It came upon the midnight clear",
         author="Edmund H. Sears", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/it_came_upon_the_midnight_clear"),
    dict(id="h050", title="O Little Town of Bethlehem", first_line="O little town of Bethlehem",
         author="Phillips Brooks", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/o_little_town_of_bethlehem"),
    dict(id="h051", title="Angels from the Realms of Glory", first_line="Angels from the realms of glory",
         author="James Montgomery", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/angels_from_the_realms_of_glory"),
    dict(id="h052", title="O Come, All Ye Faithful", first_line="O come, all ye faithful",
         author="John Francis Wade; translated by Frederick Oakeley", section="advent_christmas",
         season="Christmas", source="https://hymnary.org/text/o_come_all_ye_faithful_joyful_and_triump"),
    dict(id="h053", title="As with Gladness Men of Old", first_line="As with gladness men of old",
         author="William Chatterton Dix", section="advent_christmas", season="Christmas and Epiphany",
         source="https://hymnary.org/text/as_with_gladness_men_of_old"),
    dict(id="h054", title="Go, Tell It on the Mountain", first_line="While shepherds kept their watching",
         author="African American spiritual; adapted by John W. Work",
         section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/while_shepherds_kept_their_watching"),
    dict(id="h055", title="There's a Song in the Air", first_line="There's a song in the air",
         author="Josiah G. Holland", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/theres_a_song_in_the_air_theres_a_star"),
    dict(id="h056", title="Angels We Have Heard on High", first_line="Angels we have heard on high",
         author="Traditional French; English translation by James Chadwick", section="advent_christmas",
         season="Christmas", source="https://hymnary.org/text/angels_we_have_heard_on_high"),
    dict(id="h057", title="What Child Is This?", first_line="What child is this, who, laid to rest",
         author="William Chatterton Dix", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/what_child_is_this_who_laid_to_rest"),
    dict(id="h058", title="From Heaven Above to Earth I Come", first_line="From heaven above to earth I come",
         author="Martin Luther; English translation varies", section="advent_christmas",
         season="Christmas", source="https://hymnary.org/text/from_heaven_above_to_earth_I_come"),
    dict(id="h059", title="I Heard the Bells on Christmas Day", first_line="I heard the bells on Christmas day",
         author="Henry Wadsworth Longfellow", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/i_heard_the_bells_on_christmas_day"),
    dict(id="h060", title="See Amid the Winter's Snow", first_line="See amid the winter's snow",
         author="Edward Caswall", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/see_amid_the_winters_snow"),
    dict(id="h061", title="Silent Night, Holy Night", first_line="Silent night, holy night, all is calm",
         author="Joseph Mohr; translated by John F. Young", section="advent_christmas",
         season="Christmas", source="https://hymnary.org/text/silent_night_holy_night_all_is_calm_all"),
    dict(id="h062", title="Away in a Manger", first_line="Away in a manger, no crib for a bed",
         author="Anonymous", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/away_in_a_manger_no_crib_for_a_bed"),
    dict(id="h063", title="The First Noel", first_line="The first Noel the angel did say",
         author="Traditional English", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/the_first_nowell_the_angel_did_say"),
    dict(id="h064", title="We Three Kings of Orient Are", first_line="We three kings of Orient are",
         author="John H. Hopkins Jr.", section="advent_christmas", season="Christmas and Epiphany",
         source="https://hymnary.org/text/we_three_kings_of_orient_are"),
    dict(id="h065", title="In the Bleak Midwinter", first_line="In the bleak midwinter",
         author="Christina Rossetti", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/in_the_bleak_midwinter"),
    dict(id="h066", title="Once in Royal David's City", first_line="Once in royal David's city",
         author="Cecil Frances Alexander", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/once_in_royal_davids_city_stood_a_lowly"),
    dict(id="h067", title="God Rest Ye Merry, Gentlemen", first_line="God rest ye merry, gentlemen",
         author="Traditional English", section="advent_christmas", season="Christmas",
         source="https://hymnary.org/text/god_rest_ye_merry_gentlemen"),
    dict(id="h068", title="Good Christian Friends, Rejoice", first_line="Good Christian friends, rejoice",
         author="Traditional; translated by John Mason Neale", section="advent_christmas",
         season="Christmas", source="https://hymnary.org/text/good_christian_men_rejoice"),
    dict(id="h069", title="O Holy Night", first_line="O holy night! the stars are brightly shining",
         author="Placide Cappeau; translated by John Sullivan Dwight", section="advent_christmas",
         season="Christmas", source="https://hymnary.org/text/o_holy_night_the_stars_are_brightly_shin"),
])

# Historical editions to inspect for the linked entries. These are research
# leads, not selected texts or clearance to reproduce a modern variant.
# A chosen edition is promoted to text_edition only with a matching text file
# and provenance sidecar.
HISTORICAL_EDITION_CANDIDATES = {
    "h013": ("New Baptist Hymnal (1926), no. 321", 1926, "https://hymnary.org/hymn/NBH1926/321"),
    "h015": ("New Baptist Hymnal (1926), no. 181", 1926, "https://hymnary.org/hymn/NBH1926/181"),
    "h016": ("New Baptist Hymnal (1926), no. 228", 1926, "https://hymnary.org/hymn/NBH1926/228"),
    "h017": ("New Baptist Hymnal (1926), no. 236", 1926, "https://hymnary.org/hymn/NBH1926/236"),
    "h018": ("New Baptist Hymnal (1926), no. 359", 1926, "https://hymnary.org/hymn/NBH1926/359"),
    "h019": ("New Baptist Hymnal (1926), no. 319", 1926, "https://hymnary.org/hymn/NBH1926/319"),
    "h020": ("New Baptist Hymnal (1926), no. 322", 1926, "https://hymnary.org/hymn/NBH1926/322"),
    "h021": ("New Baptist Hymnal (1926), no. 224", 1926, "https://hymnary.org/hymn/NBH1926/224"),
    "h022": ("New Baptist Hymnal (1926), no. 233a", 1926, "https://hymnary.org/hymn/NBH1926/233a"),
    "h023": ("The School Hymnal (1920), no. 104", 1920, "https://hymnary.org/hymn/SH1920/104"),
    "h024": ("New Baptist Hymnal (1926), no. 296", 1926, "https://hymnary.org/hymn/NBH1926/296"),
    "h026": ("The Greatest Hymns (1924), no. 106", 1924, "https://hymnary.org/hymn/GH1924/106"),
    "h027": ("New Baptist Hymnal (1926), no. 327", 1926, "https://hymnary.org/hymn/NBH1926/327"),
    "h028": ("New Baptist Hymnal (1926), no. 406", 1926, "https://hymnary.org/hymn/NBH1926/406"),
    "h029": ("New Baptist Hymnal (1926), no. 34", 1926, "https://hymnary.org/hymn/NBH1926/34"),
    "h031": ("The Greatest Hymns (1924), no. 85", 1924, "https://hymnary.org/hymn/GH1924/85"),
    "h033": ("New Baptist Hymnal (1926), no. 31", 1926, "https://hymnary.org/hymn/NBH1926/31"),
    "h034": ("New Baptist Hymnal (1926), no. 52", 1926, "https://hymnary.org/hymn/NBH1926/52"),
    "h035": ("New Baptist Hymnal (1926), no. 108", 1926, "https://hymnary.org/hymn/NBH1926/108"),
    "h038": ("New Baptist Hymnal (1926), no. 369", 1926, "https://hymnary.org/hymn/NBH1926/369"),
    "h040": ("The School Hymnal (1920), no. 61", 1920, "https://hymnary.org/hymn/SH1920/61"),
    "h041": ("New Baptist Hymnal (1926), no. 93", 1926, "https://hymnary.org/hymn/NBH1926/93"),
    "h043": ("The Oxford Hymn Book (1920), no. 50", 1920, "https://hymnary.org/hymn/OxHB1920/50"),
    "h045": ("New Baptist Hymnal (1926), no. 98", 1926, "https://hymnary.org/hymn/NBH1926/98"),
    "h046": ("New Baptist Hymnal (1926), no. 83", 1926, "https://hymnary.org/hymn/NBH1926/83"),
    "h047": ("New Baptist Hymnal (1926), no. 89", 1926, "https://hymnary.org/hymn/NBH1926/89"),
    "h048": ("New Baptist Hymnal (1926), no. 94", 1926, "https://hymnary.org/hymn/NBH1926/94"),
    "h049": ("New Baptist Hymnal (1926), no. 85", 1926, "https://hymnary.org/hymn/NBH1926/85"),
    "h050": ("New Baptist Hymnal (1926), no. 82", 1926, "https://hymnary.org/hymn/NBH1926/82"),
    "h051": ("New Baptist Hymnal (1926), no. 91", 1926, "https://hymnary.org/hymn/NBH1926/91"),
    "h052": ("New Baptist Hymnal (1926), no. 90", 1926, "https://hymnary.org/hymn/NBH1926/90"),
    "h053": ("New Baptist Hymnal (1926), no. 88", 1926, "https://hymnary.org/hymn/NBH1926/88"),
    "h060": ("The Oxford Hymn Book (1920), no. 70", 1920, "https://hymnary.org/hymn/OxHB1920/70"),
    "h061": ("The Greatest Hymns (1924), no. 46", 1924, "https://hymnary.org/hymn/GH1924/46"),
    "h062": ("New Baptist Hymnal (1926), no. 92", 1926, "https://hymnary.org/hymn/NBH1926/92"),
    "h064": ("The School Hymnal (1920), no. 64", 1920, "https://hymnary.org/hymn/SH1920/64"),
    "h065": ("The Oxford Hymn Book (1920), no. 65", 1920, "https://hymnary.org/hymn/OxHB1920/65"),
    "h066": ("New Baptist Hymnal (1926), no. 84", 1926, "https://hymnary.org/hymn/NBH1926/84"),
    "h005": ("Songs of Salvation (1923), no. 70", 1923, "https://www.hymnologyarchive.com/great-is-thy-faithfulness"),
    "h006": ("Hymns for Worship (1927), no. 155", 1927, "https://hymnary.org/hymn/H4W1927/155"),
    "h025": ("The Glad Evangel (1887)", 1887, "https://hymnary.org/text/what_a_fellowship_what_a_joy_divine"),
    "h030": ("Hymns of Christ and the Christian Life (1867)", 1867, "https://www.hymnologyarchive.com/immortal-invisible"),
    "h032": ("Brightest and Best (1875)", 1875, "https://hymnary.org/text/to_god_be_the_glory_great_things_he_hath"),
    "h036": ("New Soul Winning Songs (1926), no. 250", 1926, "https://hymnary.org/hymn/NSWS1926/250"),
    "h037": ("Hymns and Sacred Poems (1739)", 1739, "https://hymnary.org/text/and_can_it_be_that_i_should_gain"),
    "h039": ("Whence-Whither and Other Poems (1898)", 1898, "https://hymnologyarchive.squarespace.com/o-the-deep-deep-love-of-jesus"),
    "h042": ("Evangelical Lutheran Hymn-Book (1912), no. 549", 1912, "https://www.gutenberg.org/files/76498/76498-h/76498-h.htm#hymn_549"),
    "h044": ("Theodore Baker English translation (1894), stanzas 1–2", 1894, "https://hymnary.org/text/lo_how_a_rose_eer_blooming"),
    "h054": ("Religious Folk Songs of the Negro (1909), Christmas Plantation Song", 1909, "https://s9.imslp.org/files/imglnks/usimg/1/10/IMSLP257855-PMLP418182-religiousfolkson00fenn_bw.pdf"),
    "h055": ("The Methodist Hymnal (1905), no. 112", 1905, "https://hymnary.org/hymn/MH1905/112"),
    "h056": ("Catholic Church Hymnal with Music (1905), no. 10", 1905, "https://hymnary.org/hymn/CCH1905/10"),
    "h057": ("Christmas Carols New and Old (1871)", 1871, "https://hymnary.org/text/what_child_is_this_who_laid_to_rest"),
    "h058": ("Evangelical Lutheran Hymn-Book (1912), no. 150", 1912, "https://www.gutenberg.org/files/76498/76498-h/76498-h.htm#hymn_150"),
    "h059": ("Household Poems (1865), Christmas Bells", 1865, "https://hymnologyarchive.squarespace.com/i-heard-the-bells-on-christmas-day"),
    "h063": ("Christmas Carols: Old English Carols (1922), The First Nowell", 1922, "https://www.gutenberg.org/files/72492/72492-h/72492-h.htm#The_First_Nowell"),
    "h067": ("Christmas Carols: Old English Carols (1922), God rest you merry, Gentlemen", 1922, "https://www.gutenberg.org/files/72492/72492-h/72492-h.htm#God_rest_you_merry_Gentlemen"),
    "h068": ("Christmas Carols: Old English Carols (1922), Good Christian Men, rejoice", 1922, "https://www.gutenberg.org/files/72492/72492-h/72492-h.htm#Good_Christian_Men_rejoice"),
    "h069": ("The School Hymnal (1920), no. 288", 1920, "https://hymnary.org/hymn/SH1920/288"),
}

CANDIDATE_NOTES = {
    "h044": "Only Baker's 1894 stanzas 1–2 are identified here; later stanzas may have separate rights.",
    "h054": "The 1909 printed variant differs from the familiar later verses and the catalog first line.",
    "h059": "The original poem has seven stanzas; many carol editions omit the Civil War stanzas.",
    "h063": "The 1922 source spells the title Nowell; compare every stanza before selecting it.",
    "h068": "The historical text says Christian Men; the catalog uses the newer inclusive title.",
}

for hymn in HYMNS:
    hymn.setdefault("text_rights", "pending")
    hymn.setdefault("text_edition", None)
    hymn.setdefault("tune", None)
    hymn.setdefault("meter", None)
    hymn["chapter"] = ("advent_christmas" if hymn["section"] == "advent_christmas"
                       else "related" if hymn.get("related_to") else "requested")
    if hymn["id"] in HISTORICAL_EDITION_CANDIDATES:
        edition, year, source = HISTORICAL_EDITION_CANDIDATES[hymn["id"]]
        hymn["candidate_edition"] = edition
        hymn["candidate_year"] = year
        hymn["candidate_source"] = source
        if hymn["id"] in CANDIDATE_NOTES:
            hymn["candidate_note"] = CANDIDATE_NOTES[hymn["id"]]
